apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma-prod-1-pvc
  namespace: uptimekuma-prod-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 500Mi
  volumeName: uptimekuma-prod-1-pv
 