---
- name: Install Wazuh agent
  hosts: "{{ hosts }}"
  become: true
  become_user: root
  roles:
    - ../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: wazuh-prod-1.srv-prod-1.home.clcreative.de
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'https'
        api_user: wazuh
        max_retries: 5
        retry_interval: 5
